
spring:
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      apache:
        http: info

hystrix:
  metrics:
    enabled: false

